@set allusersprofile=c:\programdata
@set appdata=c:\users\ibapo\appdata\roaming
@set chocolateyinstall=c:\programdata\chocolatey
@set chocolateylastpathupdate=133689907164639714
@set commandprompttype=native
@set commonprogramfiles=c:\program files\common files
@set commonprogramfiles(x86)=c:\program files (x86)\common files
@set commonprogramw6432=c:\program files\common files
@set complus_installroot=
@set complus_version=
@set computername=jdip2022
@set comspec=c:\windows\system32\cmd.exe
@set conda_bat=c:\users\ibapo\anaconda3\condabin\conda.bat
@set conda_exe=c:\users\ibapo\anaconda3\scripts\conda.exe
@set conda_shlvl=0
@set devenvdir=c:\program files\microsoft visual studio\2022\community\common7\ide\
@set dotnet_msbuild_sdk_resolver_sdks_dir=c:\program files (x86)\pvs-studio\buildtools\sdks
@set driverdata=c:\windows\system32\drivers\driverdata
@set efc_8360_1262719628=1
@set efc_8360_1592913036=1
@set efc_8360_2283032206=1
@set efc_8360_2775293581=1
@set efc_8360_3789132940=1
@set extensionsdkdir=c:\program files (x86)\microsoft sdks\windows kits\10\extensionsdks
@set external_include=c:\program files\microsoft visual studio\2022\community\vc\tools\msvc\14.38.33130\include;c:\program files\microsoft visual studio\2022\community\vc\tools\msvc\14.38.33130\atlmfc\include;c:\program files\microsoft visual studio\2022\community\vc\auxiliary\vs\include;c:\program files (x86)\windows kits\10\include\10.0.22621.0\ucrt;c:\program files (x86)\windows kits\10\\include\10.0.22621.0\\um;c:\program files (x86)\windows kits\10\\include\10.0.22621.0\\shared;c:\program files (x86)\windows kits\10\\include\10.0.22621.0\\winrt;c:\program files (x86)\windows kits\10\\include\10.0.22621.0\\cppwinrt;c:\program files (x86)\windows kits\netfxsdk\4.8\include\um
@set fps_browser_app_profile_string=internet explorer
@set fps_browser_user_profile_string=default
@set framework40version=v4.0
@set frameworkdir=c:\windows\microsoft.net\framework64\
@set frameworkdir64=c:\windows\microsoft.net\framework64\
@set frameworkversion=v4.0.30319
@set frameworkversion64=v4.0.30319
@set fsharpinstalldir=c:\program files\microsoft visual studio\2022\community\common7\ide\commonextensions\microsoft\fsharp\tools
@set gcexpconfigusedinsession=3
@set homedrive=c:
@set homepath=\users\ibapo
@set igccsvc_db=aqaaancmnd8bfderjhoawe/cl+sbaaaahtevcafhsk+vpzeblw4sxaqaaaacaaaaaaaqzgaaaaeaacaaaaavatkrgiusxhjwtdjyrj4imotwbplyw23dapk90cezkgaaaaaogaaaaaiaacaaaaahvaqqkveyexpz5mngb8d8+lwt5zebk0voa87t9milwmaaaabxp/gnrfend3no1tl2kzxh0jataqgai+5kphtiuhghevascxaviflqui6vwr/9cslsvx78nlym6b6crelcaegvjpv4an1ah3i6+2uyxnf1ed+tkj3xp9dprwfcoufx6hnaaaaacozlp4bdusshudbvtrce9v2qvzbl7d5h3ehvq64aae2ywawdat48+macsbaclbulkygszlp4wkjvs2xnbqm5mw==
@set include=c:\program files\microsoft visual studio\2022\community\vc\tools\msvc\14.38.33130\include;c:\program files\microsoft visual studio\2022\community\vc\tools\msvc\14.38.33130\atlmfc\include;c:\program files\microsoft visual studio\2022\community\vc\auxiliary\vs\include;c:\program files (x86)\windows kits\10\include\10.0.22621.0\ucrt;c:\program files (x86)\windows kits\10\\include\10.0.22621.0\\um;c:\program files (x86)\windows kits\10\\include\10.0.22621.0\\shared;c:\program files (x86)\windows kits\10\\include\10.0.22621.0\\winrt;c:\program files (x86)\windows kits\10\\include\10.0.22621.0\\cppwinrt;c:\program files (x86)\windows kits\netfxsdk\4.8\include\um
@set java_home=c:\program files\java\jdk-21
@set level_zero_v1_sdk_path=c:\program files\levelzerosdk\1.21.10\
@set lib=c:\program files\microsoft visual studio\2022\community\vc\tools\msvc\14.38.33130\atlmfc\lib\x64;c:\program files\microsoft visual studio\2022\community\vc\tools\msvc\14.38.33130\lib\x64;c:\program files (x86)\windows kits\netfxsdk\4.8\lib\um\x64;c:\program files (x86)\windows kits\10\lib\10.0.22621.0\ucrt\x64;c:\program files (x86)\windows kits\10\\lib\10.0.22621.0\\um\x64
@set libpath=c:\program files\microsoft visual studio\2022\community\vc\tools\msvc\14.38.33130\atlmfc\lib\x64;c:\program files\microsoft visual studio\2022\community\vc\tools\msvc\14.38.33130\lib\x64;c:\program files\microsoft visual studio\2022\community\vc\tools\msvc\14.38.33130\lib\x86\store\references;c:\program files (x86)\windows kits\10\unionmetadata\10.0.22621.0;c:\program files (x86)\windows kits\10\references\10.0.22621.0;c:\windows\microsoft.net\framework64\v4.0.30319
@set localappdata=c:\users\ibapo\appdata\local
@set logonserver=\\jdip2022
@set msbuildloadmicrosofttargetsreadonly=true
@set msbuild_exe_path=c:\program files (x86)\pvs-studio\buildtools\msbuild.exe
@set msmpi_benchmarks=c:\program files\microsoft mpi\benchmarks\
@set msmpi_bin=c:\program files\microsoft mpi\bin\
@set msmpi_inc=c:\program files (x86)\microsoft sdks\mpi\include\
@set msmpi_lib32=c:\program files (x86)\microsoft sdks\mpi\lib\x86\
@set msmpi_lib64=c:\program files (x86)\microsoft sdks\mpi\lib\x64\
@set netfxsdkdir=c:\program files (x86)\windows kits\netfxsdk\4.8\
@set number_of_processors=8
@set onedrive=c:\users\ibapo\onedrive
@set os=windows_nt
@set path=c:\program files\microsoft visual studio\2022\community\vc\tools\msvc\14.38.33130\bin\hostx64\x64;c:\program files\microsoft visual studio\2022\community\common7\ide\vc\vcpackages;c:\program files\microsoft visual studio\2022\community\common7\ide\commonextensions\microsoft\testwindow;c:\program files\microsoft visual studio\2022\community\common7\ide\commonextensions\microsoft\teamfoundation\team explorer;c:\program files\microsoft visual studio\2022\community\msbuild\current\bin\roslyn;c:\program files\microsoft visual studio\2022\community\team tools\performance tools\x64;c:\program files\microsoft visual studio\2022\community\team tools\performance tools;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.8 tools\x64\;c:\program files\microsoft visual studio\2022\community\common7\ide\commonextensions\microsoft\fsharp\tools;c:\program files\microsoft visual studio\2022\community\team tools\diagnosticshub\collector;c:\program files (x86)\windows kits\10\bin\10.0.22621.0\\x64;c:\program files (x86)\windows kits\10\bin\\x64;c:\program files\microsoft visual studio\2022\community\\msbuild\current\bin\amd64;c:\windows\microsoft.net\framework64\v4.0.30319;c:\program files\microsoft visual studio\2022\community\common7\ide\;c:\program files\microsoft visual studio\2022\community\common7\tools\;c:\users\ibapo\anaconda3\condabin;c:\program files\microsoft visual studio\2022\community\vc\tools\msvc\14.38.33130\bin\hostx64\x64;c:\program files (x86)\windows kits\10\bin\10.0.22621.0\x64;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.8 tools\x64;c:\program files (x86)\windows kits\10\bin\10.0.22621.0\x86;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.8 tools;c:\program files\microsoft visual studio\2022\community\common7\tools;c:\program files\microsoft visual studio\2022\community\common7\ide;c:\program files (x86)\html help workshop;c:\program files (x86)\pvs-studio\buildtools;c:\windows\microsoft.net\framework64\v4.0.30319\;c:\windows\microsoft.net\framework\v4.0.30319\;.\;c:\windows\microsoft.net\framework\v4.0.30319\;c:\python312\scripts\;c:\python312\;c:\program files\common files\oracle\java\javapath;c:\program files (x86)\common files\oracle\java\javapath;c:\program files\microsoft mpi\bin\;c:\program files\java\jdk-21\bin;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\windows\system32\openssh\;c:\program files\dotnet\;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\windows\system32\openssh\;c:\program files\microsoft sql server\client sdk\odbc\170\tools\binn\;c:\program files\git\cmd;c:\program files (x86)\pvs-studio\x64;c:\program files (x86)\windows kits\10\windows performance toolkit\;c:\program files (x86)\microsoft sql server\160\tools\binn\;c:\program files\microsoft sql server\160\tools\binn\;c:\program files\microsoft sql server\160\dts\binn\;c:\program files\azure data studio\bin;c:\program files\cmake\bin;c:\program files\docker\docker\resources\bin;c:\xampp\php\php.exe;c:\programdata\chocolatey\bin;c:\program files\nodejs\;c:\program files\microsoft sql server\150\tools\binn\;c:\program files\oracle\virtualbox\;c:\users\ibapo\appdata\local\programs\python\python311\scripts\;c:\users\ibapo\appdata\local\programs\python\python311\;c:\users\ibapo\appdata\local\programs\python\python312\scripts\;c:\users\ibapo\appdata\local\programs\python\python312\;c:\users\ibapo\appdata\local\programs\python\launcher\;c:\users\ibapo\appdata\local\microsoft\windowsapps;c:\users\ibapo\.dotnet\tools;c:\users\ibapo\appdata\local\programs\microsoft vs code\bin;c:\program files\azure data studio\bin;c:\users\ibapo\appdata\local\githubdesktop\bin;c:\users\ibapo\appdata\roaming\npm;c:\program files\microsoft visual studio\2022\community\common7\ide\commonextensions\microsoft\cmake\cmake\bin;c:\program files\microsoft visual studio\2022\community\common7\ide\commonextensions\microsoft\cmake\ninja;c:\program files\microsoft visual studio\2022\community\common7\ide\vc\linux\bin\connectionmanagerexe;c:\program files\microsoft visual studio\2022\community\vc\vcpkg
@set pathext=.com;.exe;.bat;.cmd;.vbs;.vbe;.js;.jse;.wsf;.wsh;.msc;.py;.pyw
@set pkgdefapplicationconfigfile=c:\users\ibapo\appdata\local\microsoft\visualstudio\17.0_ca1fc0cf\devenv.exe.config
@set platform=x64
@set processor_architecture=amd64
@set processor_identifier=intel64 family 6 model 140 stepping 2, genuineintel
@set processor_level=6
@set processor_revision=8c02
@set programdata=c:\programdata
@set programfiles=c:\program files
@set programfiles(x86)=c:\program files (x86)
@set programw6432=c:\program files
@set prompt=$p$g
@set psmodulepath=c:\program files\windowspowershell\modules;c:\windows\system32\windowspowershell\v1.0\modules;c:\program files (x86)\microsoft sql server\160\tools\powershell\modules\
@set public=c:\users\public
@set pvsbuildtools_extensionspath_current=c:\program files\microsoft visual studio\2022\community\msbuild
@set pvsbuildtools_extensionspath_vs2022=c:\program files\microsoft visual studio\2022\community\msbuild
@set pvsbuildtools_installdir_current=c:\program files\microsoft visual studio\2022\community
@set pvsbuildtools_installdir_vs2022=c:\program files\microsoft visual studio\2022\community
@set pvsbuildtools_netcoresdkmajorversion=9
@set pvsbuildtools_vctargetspath_current=c:\program files\microsoft visual studio\2022\community\msbuild\microsoft\vc\v170\
@set pvsbuildtools_visualstudioversion_current=17.0
@set pvs_netcoresdkspath=c:\program files\dotnet\sdk\9.0.100\sdks
@set servicehublogsessionkey=45c99961
@set sessionname=console
@set systemdrive=c:
@set systemroot=c:\windows
@set temp=c:\users\ibapo\appdata\local\temp
@set threadedwaitdialogdpicontext=-4
@set tmp=c:\users\ibapo\appdata\local\temp
@set ucrtversion=10.0.22621.0
@set universalcrtsdkdir=c:\program files (x86)\windows kits\10\
@set userdomain=jdip2022
@set userdomain_roamingprofile=jdip2022
@set username=ibapo
@set userprofile=c:\users\ibapo
@set vbox_msi_install_path=c:\program files\oracle\virtualbox\
@set vcideinstalldir=c:\program files\microsoft visual studio\2022\community\common7\ide\vc\
@set vcinstalldir=c:\program files\microsoft visual studio\2022\community\vc\
@set vcpkg_root=c:\program files\microsoft visual studio\2022\community\vc\vcpkg
@set vctoolsinstalldir=c:\program files\microsoft visual studio\2022\community\vc\tools\msvc\14.38.33130\
@set vctoolsredistdir=c:\program files\microsoft visual studio\2022\community\vc\redist\msvc\14.38.33130\
@set vctoolsversion=14.38.33130
@set visualstudiodir=c:\users\ibapo\onedrive\documents\visual studio 2022
@set visualstudioedition=microsoft visual studio community 2022
@set visualstudioversion=17.0
@set vs170comntools=c:\program files\microsoft visual studio\2022\community\common7\tools\
@set vsappiddir=c:\program files\microsoft visual studio\2022\community\common7\ide\
@set vsappidname=devenv.exe
@set vscmd_arg_app_plat=desktop
@set vscmd_arg_host_arch=x64
@set vscmd_arg_tgt_arch=x64
@set vscmd_ver=17.8.5
@set vsinstalldir=c:\program files\microsoft visual studio\2022\community\
@set vslang=1033
@set vspermonitordpiawarenessenabled.34000=true
@set vsskuedition=community
@set vs_perf_session_gcheapcount=2
@set windir=c:\windows
@set windowslibpath=c:\program files (x86)\windows kits\10\unionmetadata\10.0.22621.0;c:\program files (x86)\windows kits\10\references\10.0.22621.0
@set windowssdkbinpath=c:\program files (x86)\windows kits\10\bin\
@set windowssdkdir=c:\program files (x86)\windows kits\10\
@set windowssdklibversion=10.0.22621.0\
@set windowssdkverbinpath=c:\program files (x86)\windows kits\10\bin\10.0.22621.0\
@set windowssdkversion=10.0.22621.0\
@set windowssdk_executablepath_x64=c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.8 tools\x64\
@set windowssdk_executablepath_x86=c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.8 tools\
@set zes_enable_sysman=1
@set __dotnet_add_64bit=1
@set __dotnet_preferred_bitness=64
@set __vscmd_preinit_path=c:\users\ibapo\anaconda3\condabin;c:\program files\microsoft visual studio\2022\community\vc\tools\msvc\14.38.33130\bin\hostx64\x64;c:\program files (x86)\windows kits\10\bin\10.0.22621.0\x64;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.8 tools\x64;c:\program files (x86)\windows kits\10\bin\10.0.22621.0\x86;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.8 tools;c:\program files\microsoft visual studio\2022\community\common7\tools;c:\program files\microsoft visual studio\2022\community\common7\ide;c:\program files (x86)\html help workshop;c:\program files (x86)\pvs-studio\buildtools;c:\windows\microsoft.net\framework64\v4.0.30319\;c:\windows\microsoft.net\framework\v4.0.30319\;.\;c:\windows\microsoft.net\framework\v4.0.30319\;c:\python312\scripts\;c:\python312\;c:\program files\common files\oracle\java\javapath;c:\program files (x86)\common files\oracle\java\javapath;c:\program files\microsoft mpi\bin\;c:\program files\java\jdk-21\bin;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\windows\system32\openssh\;c:\program files\dotnet\;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\windows\system32\openssh\;c:\program files\microsoft sql server\client sdk\odbc\170\tools\binn\;c:\program files\git\cmd;c:\program files (x86)\pvs-studio\x64;c:\program files (x86)\windows kits\10\windows performance toolkit\;c:\program files (x86)\microsoft sql server\160\tools\binn\;c:\program files\microsoft sql server\160\tools\binn\;c:\program files\microsoft sql server\160\dts\binn\;c:\program files\azure data studio\bin;c:\program files\cmake\bin;c:\program files\docker\docker\resources\bin;c:\xampp\php\php.exe;c:\programdata\chocolatey\bin;c:\program files\nodejs\;c:\program files\microsoft sql server\150\tools\binn\;c:\program files\oracle\virtualbox\;c:\users\ibapo\appdata\local\programs\python\python311\scripts\;c:\users\ibapo\appdata\local\programs\python\python311\;c:\users\ibapo\appdata\local\programs\python\python312\scripts\;c:\users\ibapo\appdata\local\programs\python\python312\;c:\users\ibapo\appdata\local\programs\python\launcher\;c:\users\ibapo\appdata\local\microsoft\windowsapps;c:\users\ibapo\.dotnet\tools;c:\users\ibapo\appdata\local\programs\microsoft vs code\bin;c:\program files\azure data studio\bin;c:\users\ibapo\appdata\local\githubdesktop\bin;c:\users\ibapo\appdata\roaming\npm

@call "cl.exe" @"C:\Users\Ibapo\OneDrive\Escritorio\Projects\Orbital_Gravity_Simulator\Orbital_Gravity_Simulator\Orbital_Gravity_Simulator\main.cpp.PVS-Studio.preprocess.cmd.rsp" 2>&1